---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
Controller:
  extensions:
    - QuickFeedbackExtension
---
Only:
  moduleexists: 'cms'
---
Feedback:
  extensions:
    - FeedbackSiteTreeExtension
